spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.cfo64mwoijhv.ap-northeast-2.rds.amazonaws.com/mandarin_shop
    username: aws
    password: 1q2w3e!!

  mail:
    host: smtp.naver.com
    port: 587
    address: dlwldjs3132@naver.com
    username: dlwldjs3132@naver.com
    password: Ez0603?!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

jwt:
  secret: cM2N2aAx4N3PQ419Ds/hYBVZhIUIJMLs73Va0ul/qdGvZ2/TZAF7jjDwMz68nj1k