spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.cfo64mwoijhv.ap-northeast-2.rds.amazonaws.com/mandarin_shop
    username: aws
    password: 1q2w3e!!

jwt:
  secret: cM2N2aAx4N3PQ419Ds/hYBVZhIUIJMLs73Va0ul/qdGvZ2/TZAF7jjDwMz68nj1k